#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnitzProvider
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="NJTheater")]
	public partial class SnitzMemberDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFORUM_MEMBER(FORUM_MEMBER instance);
    partial void UpdateFORUM_MEMBER(FORUM_MEMBER instance);
    partial void DeleteFORUM_MEMBER(FORUM_MEMBER instance);
    partial void InsertFORUM_ROLE(FORUM_ROLE instance);
    partial void UpdateFORUM_ROLE(FORUM_ROLE instance);
    partial void DeleteFORUM_ROLE(FORUM_ROLE instance);
    partial void InsertFORUM_USERSINROLE(FORUM_USERSINROLE instance);
    partial void UpdateFORUM_USERSINROLE(FORUM_USERSINROLE instance);
    partial void DeleteFORUM_USERSINROLE(FORUM_USERSINROLE instance);
    #endregion
		
	
		public SnitzMemberDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SnitzMemberDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SnitzMemberDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SnitzMemberDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<FORUM_MEMBER> FORUM_MEMBERs
		{
			get
			{
				return this.GetTable<FORUM_MEMBER>();
			}
		}
		
		public System.Data.Linq.Table<FORUM_ROLE> FORUM_ROLEs
		{
			get
			{
				return this.GetTable<FORUM_ROLE>();
			}
		}
		
		public System.Data.Linq.Table<FORUM_USERSINROLE> FORUM_USERSINROLEs
		{
			get
			{
				return this.GetTable<FORUM_USERSINROLE>();
			}
		}
	}
	
	[Table(Name="dbo.FORUM_MEMBERS")]
	public partial class FORUM_MEMBER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MEMBER_ID;
		
		private System.Nullable<short> _M_STATUS;
		
		private string _M_NAME;
		
		private string _M_USERNAME;
		
		private string _M_FIRSTNAME;
		
		private string _M_LASTNAME;
		
		private string _M_PASSWORD;
		
		private string _M_EMAIL;
		
		private string _M_COUNTRY;
		
		private string _M_HOMEPAGE;
		
		private string _M_SIG;
		
		private System.Nullable<int> _M_DEFAULT_VIEW;
		
		private System.Nullable<short> _M_LEVEL;
		
		private System.Nullable<int> _M_POSTS;
		
		private string _M_DATE;
		
		private string _M_LASTHEREDATE;
		
		private string _M_LASTPOSTDATE;
		
		private string _M_TITLE;
		
		private System.Nullable<short> _M_SUBSCRIPTION;
		
		private System.Nullable<short> _M_HIDE_EMAIL;
		
		private System.Nullable<short> _M_RECEIVE_EMAIL;
		
		private string _M_LAST_IP;
		
		private string _M_IP;
		
		private string _M_OCCUPATION;
		
		private string _M_SEX;
		
		private string _M_AGE;
		
		private string _M_HOBBIES;
		
		private string _M_LNEWS;
		
		private string _M_QUOTE;
		
		private string _M_AIM;
		
		private string _M_YAHOO;
		
		private string _M_ICQ;
		
		private string _M_BIO;
		
		private string _M_MARSTATUS;
		
		private string _M_LINK1;
		
		private string _M_LINK2;
		
		private string _M_CITY;
		
		private string _M_STATE;
		
		private string _M_PHOTO_URL;
		
		private System.Guid _rowguid;
		
		private string _M_MSN;
		
		private string _M_KEY;
		
		private string _M_NEWEMAIL;
		
		private System.Nullable<short> _M_SHA256;
		
		private string _M_PWKEY;
		
		private System.Nullable<short> _M_VIEW_SIG;
		
		private string _M_DOB;
		
		private System.Nullable<short> _M_SIG_DEFAULT;
		
		private EntitySet<FORUM_USERSINROLE> _FORUM_USERSINROLEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMEMBER_IDChanging(int value);
    partial void OnMEMBER_IDChanged();
    partial void OnM_STATUSChanging(System.Nullable<short> value);
    partial void OnM_STATUSChanged();
    partial void OnM_NAMEChanging(string value);
    partial void OnM_NAMEChanged();
    partial void OnM_USERNAMEChanging(string value);
    partial void OnM_USERNAMEChanged();
    partial void OnM_FIRSTNAMEChanging(string value);
    partial void OnM_FIRSTNAMEChanged();
    partial void OnM_LASTNAMEChanging(string value);
    partial void OnM_LASTNAMEChanged();
    partial void OnM_PASSWORDChanging(string value);
    partial void OnM_PASSWORDChanged();
    partial void OnM_EMAILChanging(string value);
    partial void OnM_EMAILChanged();
    partial void OnM_COUNTRYChanging(string value);
    partial void OnM_COUNTRYChanged();
    partial void OnM_HOMEPAGEChanging(string value);
    partial void OnM_HOMEPAGEChanged();
    partial void OnM_SIGChanging(string value);
    partial void OnM_SIGChanged();
    partial void OnM_DEFAULT_VIEWChanging(System.Nullable<int> value);
    partial void OnM_DEFAULT_VIEWChanged();
    partial void OnM_LEVELChanging(System.Nullable<short> value);
    partial void OnM_LEVELChanged();
    partial void OnM_POSTSChanging(System.Nullable<int> value);
    partial void OnM_POSTSChanged();
    partial void OnM_DATEChanging(string value);
    partial void OnM_DATEChanged();
    partial void OnM_LASTHEREDATEChanging(string value);
    partial void OnM_LASTHEREDATEChanged();
    partial void OnM_LASTPOSTDATEChanging(string value);
    partial void OnM_LASTPOSTDATEChanged();
    partial void OnM_TITLEChanging(string value);
    partial void OnM_TITLEChanged();
    partial void OnM_SUBSCRIPTIONChanging(System.Nullable<short> value);
    partial void OnM_SUBSCRIPTIONChanged();
    partial void OnM_HIDE_EMAILChanging(System.Nullable<short> value);
    partial void OnM_HIDE_EMAILChanged();
    partial void OnM_RECEIVE_EMAILChanging(System.Nullable<short> value);
    partial void OnM_RECEIVE_EMAILChanged();
    partial void OnM_LAST_IPChanging(string value);
    partial void OnM_LAST_IPChanged();
    partial void OnM_IPChanging(string value);
    partial void OnM_IPChanged();
    partial void OnM_OCCUPATIONChanging(string value);
    partial void OnM_OCCUPATIONChanged();
    partial void OnM_SEXChanging(string value);
    partial void OnM_SEXChanged();
    partial void OnM_AGEChanging(string value);
    partial void OnM_AGEChanged();
    partial void OnM_HOBBIESChanging(string value);
    partial void OnM_HOBBIESChanged();
    partial void OnM_LNEWSChanging(string value);
    partial void OnM_LNEWSChanged();
    partial void OnM_QUOTEChanging(string value);
    partial void OnM_QUOTEChanged();
    partial void OnM_AIMChanging(string value);
    partial void OnM_AIMChanged();
    partial void OnM_YAHOOChanging(string value);
    partial void OnM_YAHOOChanged();
    partial void OnM_ICQChanging(string value);
    partial void OnM_ICQChanged();
    partial void OnM_BIOChanging(string value);
    partial void OnM_BIOChanged();
    partial void OnM_MARSTATUSChanging(string value);
    partial void OnM_MARSTATUSChanged();
    partial void OnM_LINK1Changing(string value);
    partial void OnM_LINK1Changed();
    partial void OnM_LINK2Changing(string value);
    partial void OnM_LINK2Changed();
    partial void OnM_CITYChanging(string value);
    partial void OnM_CITYChanged();
    partial void OnM_STATEChanging(string value);
    partial void OnM_STATEChanged();
    partial void OnM_PHOTO_URLChanging(string value);
    partial void OnM_PHOTO_URLChanged();
    partial void OnrowguidChanging(System.Guid value);
    partial void OnrowguidChanged();
    partial void OnM_MSNChanging(string value);
    partial void OnM_MSNChanged();
    partial void OnM_KEYChanging(string value);
    partial void OnM_KEYChanged();
    partial void OnM_NEWEMAILChanging(string value);
    partial void OnM_NEWEMAILChanged();
    partial void OnM_SHA256Changing(System.Nullable<short> value);
    partial void OnM_SHA256Changed();
    partial void OnM_PWKEYChanging(string value);
    partial void OnM_PWKEYChanged();
    partial void OnM_VIEW_SIGChanging(System.Nullable<short> value);
    partial void OnM_VIEW_SIGChanged();
    partial void OnM_DOBChanging(string value);
    partial void OnM_DOBChanged();
    partial void OnM_SIG_DEFAULTChanging(System.Nullable<short> value);
    partial void OnM_SIG_DEFAULTChanged();
    #endregion
		
		public FORUM_MEMBER()
		{
			this._FORUM_USERSINROLEs = new EntitySet<FORUM_USERSINROLE>(new Action<FORUM_USERSINROLE>(this.attach_FORUM_USERSINROLEs), new Action<FORUM_USERSINROLE>(this.detach_FORUM_USERSINROLEs));
			OnCreated();
		}
		
		[Column(Storage="_MEMBER_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MEMBER_ID
		{
			get
			{
				return this._MEMBER_ID;
			}
			set
			{
				if ((this._MEMBER_ID != value))
				{
					this.OnMEMBER_IDChanging(value);
					this.SendPropertyChanging();
					this._MEMBER_ID = value;
					this.SendPropertyChanged("MEMBER_ID");
					this.OnMEMBER_IDChanged();
				}
			}
		}
		
		[Column(Storage="_M_STATUS", DbType="SmallInt")]
		public System.Nullable<short> M_STATUS
		{
			get
			{
				return this._M_STATUS;
			}
			set
			{
				if ((this._M_STATUS != value))
				{
					this.OnM_STATUSChanging(value);
					this.SendPropertyChanging();
					this._M_STATUS = value;
					this.SendPropertyChanged("M_STATUS");
					this.OnM_STATUSChanged();
				}
			}
		}
		
		[Column(Storage="_M_NAME", DbType="NVarChar(75)")]
		public string M_NAME
		{
			get
			{
				return this._M_NAME;
			}
			set
			{
				if ((this._M_NAME != value))
				{
					this.OnM_NAMEChanging(value);
					this.SendPropertyChanging();
					this._M_NAME = value;
					this.SendPropertyChanged("M_NAME");
					this.OnM_NAMEChanged();
				}
			}
		}
		
		[Column(Storage="_M_USERNAME", DbType="NVarChar(150)")]
		public string M_USERNAME
		{
			get
			{
				return this._M_USERNAME;
			}
			set
			{
				if ((this._M_USERNAME != value))
				{
					this.OnM_USERNAMEChanging(value);
					this.SendPropertyChanging();
					this._M_USERNAME = value;
					this.SendPropertyChanged("M_USERNAME");
					this.OnM_USERNAMEChanged();
				}
			}
		}
		
		[Column(Storage="_M_FIRSTNAME", DbType="NVarChar(100)")]
		public string M_FIRSTNAME
		{
			get
			{
				return this._M_FIRSTNAME;
			}
			set
			{
				if ((this._M_FIRSTNAME != value))
				{
					this.OnM_FIRSTNAMEChanging(value);
					this.SendPropertyChanging();
					this._M_FIRSTNAME = value;
					this.SendPropertyChanged("M_FIRSTNAME");
					this.OnM_FIRSTNAMEChanged();
				}
			}
		}
		
		[Column(Storage="_M_LASTNAME", DbType="NVarChar(100)")]
		public string M_LASTNAME
		{
			get
			{
				return this._M_LASTNAME;
			}
			set
			{
				if ((this._M_LASTNAME != value))
				{
					this.OnM_LASTNAMEChanging(value);
					this.SendPropertyChanging();
					this._M_LASTNAME = value;
					this.SendPropertyChanged("M_LASTNAME");
					this.OnM_LASTNAMEChanged();
				}
			}
		}
		
		[Column(Storage="_M_PASSWORD", DbType="NVarChar(65)")]
		public string M_PASSWORD
		{
			get
			{
				return this._M_PASSWORD;
			}
			set
			{
				if ((this._M_PASSWORD != value))
				{
					this.OnM_PASSWORDChanging(value);
					this.SendPropertyChanging();
					this._M_PASSWORD = value;
					this.SendPropertyChanged("M_PASSWORD");
					this.OnM_PASSWORDChanged();
				}
			}
		}
		
		[Column(Storage="_M_EMAIL", DbType="NVarChar(50)")]
		public string M_EMAIL
		{
			get
			{
				return this._M_EMAIL;
			}
			set
			{
				if ((this._M_EMAIL != value))
				{
					this.OnM_EMAILChanging(value);
					this.SendPropertyChanging();
					this._M_EMAIL = value;
					this.SendPropertyChanged("M_EMAIL");
					this.OnM_EMAILChanged();
				}
			}
		}
		
		[Column(Storage="_M_COUNTRY", DbType="NVarChar(50)")]
		public string M_COUNTRY
		{
			get
			{
				return this._M_COUNTRY;
			}
			set
			{
				if ((this._M_COUNTRY != value))
				{
					this.OnM_COUNTRYChanging(value);
					this.SendPropertyChanging();
					this._M_COUNTRY = value;
					this.SendPropertyChanged("M_COUNTRY");
					this.OnM_COUNTRYChanged();
				}
			}
		}
		
		[Column(Storage="_M_HOMEPAGE", DbType="NVarChar(255)")]
		public string M_HOMEPAGE
		{
			get
			{
				return this._M_HOMEPAGE;
			}
			set
			{
				if ((this._M_HOMEPAGE != value))
				{
					this.OnM_HOMEPAGEChanging(value);
					this.SendPropertyChanging();
					this._M_HOMEPAGE = value;
					this.SendPropertyChanged("M_HOMEPAGE");
					this.OnM_HOMEPAGEChanged();
				}
			}
		}
		
		[Column(Storage="_M_SIG", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string M_SIG
		{
			get
			{
				return this._M_SIG;
			}
			set
			{
				if ((this._M_SIG != value))
				{
					this.OnM_SIGChanging(value);
					this.SendPropertyChanging();
					this._M_SIG = value;
					this.SendPropertyChanged("M_SIG");
					this.OnM_SIGChanged();
				}
			}
		}
		
		[Column(Storage="_M_DEFAULT_VIEW", DbType="Int")]
		public System.Nullable<int> M_DEFAULT_VIEW
		{
			get
			{
				return this._M_DEFAULT_VIEW;
			}
			set
			{
				if ((this._M_DEFAULT_VIEW != value))
				{
					this.OnM_DEFAULT_VIEWChanging(value);
					this.SendPropertyChanging();
					this._M_DEFAULT_VIEW = value;
					this.SendPropertyChanged("M_DEFAULT_VIEW");
					this.OnM_DEFAULT_VIEWChanged();
				}
			}
		}
		
		[Column(Storage="_M_LEVEL", DbType="SmallInt")]
		public System.Nullable<short> M_LEVEL
		{
			get
			{
				return this._M_LEVEL;
			}
			set
			{
				if ((this._M_LEVEL != value))
				{
					this.OnM_LEVELChanging(value);
					this.SendPropertyChanging();
					this._M_LEVEL = value;
					this.SendPropertyChanged("M_LEVEL");
					this.OnM_LEVELChanged();
				}
			}
		}
		
		[Column(Storage="_M_POSTS", DbType="Int")]
		public System.Nullable<int> M_POSTS
		{
			get
			{
				return this._M_POSTS;
			}
			set
			{
				if ((this._M_POSTS != value))
				{
					this.OnM_POSTSChanging(value);
					this.SendPropertyChanging();
					this._M_POSTS = value;
					this.SendPropertyChanged("M_POSTS");
					this.OnM_POSTSChanged();
				}
			}
		}
		
		[Column(Storage="_M_DATE", DbType="NVarChar(50)")]
		public string M_DATE
		{
			get
			{
				return this._M_DATE;
			}
			set
			{
				if ((this._M_DATE != value))
				{
					this.OnM_DATEChanging(value);
					this.SendPropertyChanging();
					this._M_DATE = value;
					this.SendPropertyChanged("M_DATE");
					this.OnM_DATEChanged();
				}
			}
		}
		
		[Column(Storage="_M_LASTHEREDATE", DbType="NVarChar(50)")]
		public string M_LASTHEREDATE
		{
			get
			{
				return this._M_LASTHEREDATE;
			}
			set
			{
				if ((this._M_LASTHEREDATE != value))
				{
					this.OnM_LASTHEREDATEChanging(value);
					this.SendPropertyChanging();
					this._M_LASTHEREDATE = value;
					this.SendPropertyChanged("M_LASTHEREDATE");
					this.OnM_LASTHEREDATEChanged();
				}
			}
		}
		
		[Column(Storage="_M_LASTPOSTDATE", DbType="NVarChar(50)")]
		public string M_LASTPOSTDATE
		{
			get
			{
				return this._M_LASTPOSTDATE;
			}
			set
			{
				if ((this._M_LASTPOSTDATE != value))
				{
					this.OnM_LASTPOSTDATEChanging(value);
					this.SendPropertyChanging();
					this._M_LASTPOSTDATE = value;
					this.SendPropertyChanged("M_LASTPOSTDATE");
					this.OnM_LASTPOSTDATEChanged();
				}
			}
		}
		
		[Column(Storage="_M_TITLE", DbType="NVarChar(50)")]
		public string M_TITLE
		{
			get
			{
				return this._M_TITLE;
			}
			set
			{
				if ((this._M_TITLE != value))
				{
					this.OnM_TITLEChanging(value);
					this.SendPropertyChanging();
					this._M_TITLE = value;
					this.SendPropertyChanged("M_TITLE");
					this.OnM_TITLEChanged();
				}
			}
		}
		
		[Column(Storage="_M_SUBSCRIPTION", DbType="SmallInt")]
		public System.Nullable<short> M_SUBSCRIPTION
		{
			get
			{
				return this._M_SUBSCRIPTION;
			}
			set
			{
				if ((this._M_SUBSCRIPTION != value))
				{
					this.OnM_SUBSCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._M_SUBSCRIPTION = value;
					this.SendPropertyChanged("M_SUBSCRIPTION");
					this.OnM_SUBSCRIPTIONChanged();
				}
			}
		}
		
		[Column(Storage="_M_HIDE_EMAIL", DbType="SmallInt")]
		public System.Nullable<short> M_HIDE_EMAIL
		{
			get
			{
				return this._M_HIDE_EMAIL;
			}
			set
			{
				if ((this._M_HIDE_EMAIL != value))
				{
					this.OnM_HIDE_EMAILChanging(value);
					this.SendPropertyChanging();
					this._M_HIDE_EMAIL = value;
					this.SendPropertyChanged("M_HIDE_EMAIL");
					this.OnM_HIDE_EMAILChanged();
				}
			}
		}
		
		[Column(Storage="_M_RECEIVE_EMAIL", DbType="SmallInt")]
		public System.Nullable<short> M_RECEIVE_EMAIL
		{
			get
			{
				return this._M_RECEIVE_EMAIL;
			}
			set
			{
				if ((this._M_RECEIVE_EMAIL != value))
				{
					this.OnM_RECEIVE_EMAILChanging(value);
					this.SendPropertyChanging();
					this._M_RECEIVE_EMAIL = value;
					this.SendPropertyChanged("M_RECEIVE_EMAIL");
					this.OnM_RECEIVE_EMAILChanged();
				}
			}
		}
		
		[Column(Storage="_M_LAST_IP", DbType="NVarChar(50)")]
		public string M_LAST_IP
		{
			get
			{
				return this._M_LAST_IP;
			}
			set
			{
				if ((this._M_LAST_IP != value))
				{
					this.OnM_LAST_IPChanging(value);
					this.SendPropertyChanging();
					this._M_LAST_IP = value;
					this.SendPropertyChanged("M_LAST_IP");
					this.OnM_LAST_IPChanged();
				}
			}
		}
		
		[Column(Storage="_M_IP", DbType="NVarChar(50)")]
		public string M_IP
		{
			get
			{
				return this._M_IP;
			}
			set
			{
				if ((this._M_IP != value))
				{
					this.OnM_IPChanging(value);
					this.SendPropertyChanging();
					this._M_IP = value;
					this.SendPropertyChanged("M_IP");
					this.OnM_IPChanged();
				}
			}
		}
		
		[Column(Storage="_M_OCCUPATION", DbType="NVarChar(255)")]
		public string M_OCCUPATION
		{
			get
			{
				return this._M_OCCUPATION;
			}
			set
			{
				if ((this._M_OCCUPATION != value))
				{
					this.OnM_OCCUPATIONChanging(value);
					this.SendPropertyChanging();
					this._M_OCCUPATION = value;
					this.SendPropertyChanged("M_OCCUPATION");
					this.OnM_OCCUPATIONChanged();
				}
			}
		}
		
		[Column(Storage="_M_SEX", DbType="NVarChar(50)")]
		public string M_SEX
		{
			get
			{
				return this._M_SEX;
			}
			set
			{
				if ((this._M_SEX != value))
				{
					this.OnM_SEXChanging(value);
					this.SendPropertyChanging();
					this._M_SEX = value;
					this.SendPropertyChanged("M_SEX");
					this.OnM_SEXChanged();
				}
			}
		}
		
		[Column(Storage="_M_AGE", DbType="NVarChar(10)")]
		public string M_AGE
		{
			get
			{
				return this._M_AGE;
			}
			set
			{
				if ((this._M_AGE != value))
				{
					this.OnM_AGEChanging(value);
					this.SendPropertyChanging();
					this._M_AGE = value;
					this.SendPropertyChanged("M_AGE");
					this.OnM_AGEChanged();
				}
			}
		}
		
		[Column(Storage="_M_HOBBIES", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string M_HOBBIES
		{
			get
			{
				return this._M_HOBBIES;
			}
			set
			{
				if ((this._M_HOBBIES != value))
				{
					this.OnM_HOBBIESChanging(value);
					this.SendPropertyChanging();
					this._M_HOBBIES = value;
					this.SendPropertyChanged("M_HOBBIES");
					this.OnM_HOBBIESChanged();
				}
			}
		}
		
		[Column(Storage="_M_LNEWS", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string M_LNEWS
		{
			get
			{
				return this._M_LNEWS;
			}
			set
			{
				if ((this._M_LNEWS != value))
				{
					this.OnM_LNEWSChanging(value);
					this.SendPropertyChanging();
					this._M_LNEWS = value;
					this.SendPropertyChanged("M_LNEWS");
					this.OnM_LNEWSChanged();
				}
			}
		}
		
		[Column(Storage="_M_QUOTE", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string M_QUOTE
		{
			get
			{
				return this._M_QUOTE;
			}
			set
			{
				if ((this._M_QUOTE != value))
				{
					this.OnM_QUOTEChanging(value);
					this.SendPropertyChanging();
					this._M_QUOTE = value;
					this.SendPropertyChanged("M_QUOTE");
					this.OnM_QUOTEChanged();
				}
			}
		}
		
		[Column(Storage="_M_AIM", DbType="NVarChar(150)")]
		public string M_AIM
		{
			get
			{
				return this._M_AIM;
			}
			set
			{
				if ((this._M_AIM != value))
				{
					this.OnM_AIMChanging(value);
					this.SendPropertyChanging();
					this._M_AIM = value;
					this.SendPropertyChanged("M_AIM");
					this.OnM_AIMChanged();
				}
			}
		}
		
		[Column(Storage="_M_YAHOO", DbType="NVarChar(150)")]
		public string M_YAHOO
		{
			get
			{
				return this._M_YAHOO;
			}
			set
			{
				if ((this._M_YAHOO != value))
				{
					this.OnM_YAHOOChanging(value);
					this.SendPropertyChanging();
					this._M_YAHOO = value;
					this.SendPropertyChanged("M_YAHOO");
					this.OnM_YAHOOChanged();
				}
			}
		}
		
		[Column(Storage="_M_ICQ", DbType="NVarChar(150)")]
		public string M_ICQ
		{
			get
			{
				return this._M_ICQ;
			}
			set
			{
				if ((this._M_ICQ != value))
				{
					this.OnM_ICQChanging(value);
					this.SendPropertyChanging();
					this._M_ICQ = value;
					this.SendPropertyChanged("M_ICQ");
					this.OnM_ICQChanged();
				}
			}
		}
		
		[Column(Storage="_M_BIO", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string M_BIO
		{
			get
			{
				return this._M_BIO;
			}
			set
			{
				if ((this._M_BIO != value))
				{
					this.OnM_BIOChanging(value);
					this.SendPropertyChanging();
					this._M_BIO = value;
					this.SendPropertyChanged("M_BIO");
					this.OnM_BIOChanged();
				}
			}
		}
		
		[Column(Storage="_M_MARSTATUS", DbType="NVarChar(100)")]
		public string M_MARSTATUS
		{
			get
			{
				return this._M_MARSTATUS;
			}
			set
			{
				if ((this._M_MARSTATUS != value))
				{
					this.OnM_MARSTATUSChanging(value);
					this.SendPropertyChanging();
					this._M_MARSTATUS = value;
					this.SendPropertyChanged("M_MARSTATUS");
					this.OnM_MARSTATUSChanged();
				}
			}
		}
		
		[Column(Storage="_M_LINK1", DbType="NVarChar(255)")]
		public string M_LINK1
		{
			get
			{
				return this._M_LINK1;
			}
			set
			{
				if ((this._M_LINK1 != value))
				{
					this.OnM_LINK1Changing(value);
					this.SendPropertyChanging();
					this._M_LINK1 = value;
					this.SendPropertyChanged("M_LINK1");
					this.OnM_LINK1Changed();
				}
			}
		}
		
		[Column(Storage="_M_LINK2", DbType="NVarChar(255)")]
		public string M_LINK2
		{
			get
			{
				return this._M_LINK2;
			}
			set
			{
				if ((this._M_LINK2 != value))
				{
					this.OnM_LINK2Changing(value);
					this.SendPropertyChanging();
					this._M_LINK2 = value;
					this.SendPropertyChanged("M_LINK2");
					this.OnM_LINK2Changed();
				}
			}
		}
		
		[Column(Storage="_M_CITY", DbType="NVarChar(100)")]
		public string M_CITY
		{
			get
			{
				return this._M_CITY;
			}
			set
			{
				if ((this._M_CITY != value))
				{
					this.OnM_CITYChanging(value);
					this.SendPropertyChanging();
					this._M_CITY = value;
					this.SendPropertyChanged("M_CITY");
					this.OnM_CITYChanged();
				}
			}
		}
		
		[Column(Storage="_M_STATE", DbType="NVarChar(100)")]
		public string M_STATE
		{
			get
			{
				return this._M_STATE;
			}
			set
			{
				if ((this._M_STATE != value))
				{
					this.OnM_STATEChanging(value);
					this.SendPropertyChanging();
					this._M_STATE = value;
					this.SendPropertyChanged("M_STATE");
					this.OnM_STATEChanged();
				}
			}
		}
		
		[Column(Storage="_M_PHOTO_URL", DbType="NVarChar(255)")]
		public string M_PHOTO_URL
		{
			get
			{
				return this._M_PHOTO_URL;
			}
			set
			{
				if ((this._M_PHOTO_URL != value))
				{
					this.OnM_PHOTO_URLChanging(value);
					this.SendPropertyChanging();
					this._M_PHOTO_URL = value;
					this.SendPropertyChanged("M_PHOTO_URL");
					this.OnM_PHOTO_URLChanged();
				}
			}
		}
		
		[Column(Storage="_rowguid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid rowguid
		{
			get
			{
				return this._rowguid;
			}
			set
			{
				if ((this._rowguid != value))
				{
					this.OnrowguidChanging(value);
					this.SendPropertyChanging();
					this._rowguid = value;
					this.SendPropertyChanged("rowguid");
					this.OnrowguidChanged();
				}
			}
		}
		
		[Column(Storage="_M_MSN", DbType="NVarChar(150)")]
		public string M_MSN
		{
			get
			{
				return this._M_MSN;
			}
			set
			{
				if ((this._M_MSN != value))
				{
					this.OnM_MSNChanging(value);
					this.SendPropertyChanging();
					this._M_MSN = value;
					this.SendPropertyChanged("M_MSN");
					this.OnM_MSNChanged();
				}
			}
		}
		
		[Column(Storage="_M_KEY", DbType="NVarChar(32)")]
		public string M_KEY
		{
			get
			{
				return this._M_KEY;
			}
			set
			{
				if ((this._M_KEY != value))
				{
					this.OnM_KEYChanging(value);
					this.SendPropertyChanging();
					this._M_KEY = value;
					this.SendPropertyChanged("M_KEY");
					this.OnM_KEYChanged();
				}
			}
		}
		
		[Column(Storage="_M_NEWEMAIL", DbType="NVarChar(50)")]
		public string M_NEWEMAIL
		{
			get
			{
				return this._M_NEWEMAIL;
			}
			set
			{
				if ((this._M_NEWEMAIL != value))
				{
					this.OnM_NEWEMAILChanging(value);
					this.SendPropertyChanging();
					this._M_NEWEMAIL = value;
					this.SendPropertyChanged("M_NEWEMAIL");
					this.OnM_NEWEMAILChanged();
				}
			}
		}
		
		[Column(Storage="_M_SHA256", DbType="SmallInt")]
		public System.Nullable<short> M_SHA256
		{
			get
			{
				return this._M_SHA256;
			}
			set
			{
				if ((this._M_SHA256 != value))
				{
					this.OnM_SHA256Changing(value);
					this.SendPropertyChanging();
					this._M_SHA256 = value;
					this.SendPropertyChanged("M_SHA256");
					this.OnM_SHA256Changed();
				}
			}
		}
		
		[Column(Storage="_M_PWKEY", DbType="NVarChar(32)")]
		public string M_PWKEY
		{
			get
			{
				return this._M_PWKEY;
			}
			set
			{
				if ((this._M_PWKEY != value))
				{
					this.OnM_PWKEYChanging(value);
					this.SendPropertyChanging();
					this._M_PWKEY = value;
					this.SendPropertyChanged("M_PWKEY");
					this.OnM_PWKEYChanged();
				}
			}
		}
		
		[Column(Storage="_M_VIEW_SIG", DbType="SmallInt")]
		public System.Nullable<short> M_VIEW_SIG
		{
			get
			{
				return this._M_VIEW_SIG;
			}
			set
			{
				if ((this._M_VIEW_SIG != value))
				{
					this.OnM_VIEW_SIGChanging(value);
					this.SendPropertyChanging();
					this._M_VIEW_SIG = value;
					this.SendPropertyChanged("M_VIEW_SIG");
					this.OnM_VIEW_SIGChanged();
				}
			}
		}
		
		[Column(Storage="_M_DOB", DbType="NVarChar(8)")]
		public string M_DOB
		{
			get
			{
				return this._M_DOB;
			}
			set
			{
				if ((this._M_DOB != value))
				{
					this.OnM_DOBChanging(value);
					this.SendPropertyChanging();
					this._M_DOB = value;
					this.SendPropertyChanged("M_DOB");
					this.OnM_DOBChanged();
				}
			}
		}
		
		[Column(Storage="_M_SIG_DEFAULT", DbType="SmallInt")]
		public System.Nullable<short> M_SIG_DEFAULT
		{
			get
			{
				return this._M_SIG_DEFAULT;
			}
			set
			{
				if ((this._M_SIG_DEFAULT != value))
				{
					this.OnM_SIG_DEFAULTChanging(value);
					this.SendPropertyChanging();
					this._M_SIG_DEFAULT = value;
					this.SendPropertyChanged("M_SIG_DEFAULT");
					this.OnM_SIG_DEFAULTChanged();
				}
			}
		}
		
		[Association(Name="FORUM_MEMBER_FORUM_USERSINROLE", Storage="_FORUM_USERSINROLEs", OtherKey="MEMBER_ID")]
		public EntitySet<FORUM_USERSINROLE> FORUM_USERSINROLEs
		{
			get
			{
				return this._FORUM_USERSINROLEs;
			}
			set
			{
				this._FORUM_USERSINROLEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FORUM_USERSINROLEs(FORUM_USERSINROLE entity)
		{
			this.SendPropertyChanging();
			entity.FORUM_MEMBER = this;
		}
		
		private void detach_FORUM_USERSINROLEs(FORUM_USERSINROLE entity)
		{
			this.SendPropertyChanging();
			entity.FORUM_MEMBER = null;
		}
	}
	
	[Table(Name="dbo.FORUM_ROLES")]
	public partial class FORUM_ROLE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RoleID;
		
		private string _Name;
		
		private string _Description;
		
		private string _ModUser;
		
		private System.DateTime _ModTime;
		
		private EntitySet<FORUM_USERSINROLE> _FORUM_USERSINROLEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRoleIDChanging(int value);
    partial void OnRoleIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnModUserChanging(string value);
    partial void OnModUserChanged();
    partial void OnModTimeChanging(System.DateTime value);
    partial void OnModTimeChanged();
    #endregion
		
		public FORUM_ROLE()
		{
			this._FORUM_USERSINROLEs = new EntitySet<FORUM_USERSINROLE>(new Action<FORUM_USERSINROLE>(this.attach_FORUM_USERSINROLEs), new Action<FORUM_USERSINROLE>(this.detach_FORUM_USERSINROLEs));
			OnCreated();
		}
		
		[Column(Storage="_RoleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this.OnRoleIDChanging(value);
					this.SendPropertyChanging();
					this._RoleID = value;
					this.SendPropertyChanged("RoleID");
					this.OnRoleIDChanged();
				}
			}
		}
		
		[Column(Storage="_Name", DbType="NChar(25) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[Column(Storage="_Description", DbType="NVarChar(250)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_ModUser", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ModUser
		{
			get
			{
				return this._ModUser;
			}
			set
			{
				if ((this._ModUser != value))
				{
					this.OnModUserChanging(value);
					this.SendPropertyChanging();
					this._ModUser = value;
					this.SendPropertyChanged("ModUser");
					this.OnModUserChanged();
				}
			}
		}
		
		[Column(Storage="_ModTime", DbType="DateTime NOT NULL")]
		public System.DateTime ModTime
		{
			get
			{
				return this._ModTime;
			}
			set
			{
				if ((this._ModTime != value))
				{
					this.OnModTimeChanging(value);
					this.SendPropertyChanging();
					this._ModTime = value;
					this.SendPropertyChanged("ModTime");
					this.OnModTimeChanged();
				}
			}
		}
		
		[Association(Name="FORUM_ROLE_FORUM_USERSINROLE", Storage="_FORUM_USERSINROLEs", OtherKey="ROLEID")]
		public EntitySet<FORUM_USERSINROLE> FORUM_USERSINROLEs
		{
			get
			{
				return this._FORUM_USERSINROLEs;
			}
			set
			{
				this._FORUM_USERSINROLEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FORUM_USERSINROLEs(FORUM_USERSINROLE entity)
		{
			this.SendPropertyChanging();
			entity.FORUM_ROLE = this;
		}
		
		private void detach_FORUM_USERSINROLEs(FORUM_USERSINROLE entity)
		{
			this.SendPropertyChanging();
			entity.FORUM_ROLE = null;
		}
	}
	
	[Table(Name="dbo.FORUM_USERSINROLES")]
	public partial class FORUM_USERSINROLE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _MEMBER_ID;
		
		private int _ROLEID;
		
		private string _ModUser;
		
		private System.DateTime _ModTime;
		
		private EntityRef<FORUM_MEMBER> _FORUM_MEMBER;
		
		private EntityRef<FORUM_ROLE> _FORUM_ROLE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMEMBER_IDChanging(int value);
    partial void OnMEMBER_IDChanged();
    partial void OnROLEIDChanging(int value);
    partial void OnROLEIDChanged();
    partial void OnModUserChanging(string value);
    partial void OnModUserChanged();
    partial void OnModTimeChanging(System.DateTime value);
    partial void OnModTimeChanged();
    #endregion
		
		public FORUM_USERSINROLE()
		{
			this._FORUM_MEMBER = default(EntityRef<FORUM_MEMBER>);
			this._FORUM_ROLE = default(EntityRef<FORUM_ROLE>);
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_MEMBER_ID", DbType="Int NOT NULL")]
		public int MEMBER_ID
		{
			get
			{
				return this._MEMBER_ID;
			}
			set
			{
				if ((this._MEMBER_ID != value))
				{
					if (this._FORUM_MEMBER.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMEMBER_IDChanging(value);
					this.SendPropertyChanging();
					this._MEMBER_ID = value;
					this.SendPropertyChanged("MEMBER_ID");
					this.OnMEMBER_IDChanged();
				}
			}
		}
		
		[Column(Storage="_ROLEID", DbType="Int NOT NULL")]
		public int ROLEID
		{
			get
			{
				return this._ROLEID;
			}
			set
			{
				if ((this._ROLEID != value))
				{
					if (this._FORUM_ROLE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnROLEIDChanging(value);
					this.SendPropertyChanging();
					this._ROLEID = value;
					this.SendPropertyChanged("ROLEID");
					this.OnROLEIDChanged();
				}
			}
		}
		
		[Column(Storage="_ModUser", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ModUser
		{
			get
			{
				return this._ModUser;
			}
			set
			{
				if ((this._ModUser != value))
				{
					this.OnModUserChanging(value);
					this.SendPropertyChanging();
					this._ModUser = value;
					this.SendPropertyChanged("ModUser");
					this.OnModUserChanged();
				}
			}
		}
		
		[Column(Storage="_ModTime", DbType="DateTime NOT NULL")]
		public System.DateTime ModTime
		{
			get
			{
				return this._ModTime;
			}
			set
			{
				if ((this._ModTime != value))
				{
					this.OnModTimeChanging(value);
					this.SendPropertyChanging();
					this._ModTime = value;
					this.SendPropertyChanged("ModTime");
					this.OnModTimeChanged();
				}
			}
		}
		
		[Association(Name="FORUM_MEMBER_FORUM_USERSINROLE", Storage="_FORUM_MEMBER", ThisKey="MEMBER_ID", IsForeignKey=true)]
		public FORUM_MEMBER FORUM_MEMBER
		{
			get
			{
				return this._FORUM_MEMBER.Entity;
			}
			set
			{
				FORUM_MEMBER previousValue = this._FORUM_MEMBER.Entity;
				if (((previousValue != value) 
							|| (this._FORUM_MEMBER.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FORUM_MEMBER.Entity = null;
						previousValue.FORUM_USERSINROLEs.Remove(this);
					}
					this._FORUM_MEMBER.Entity = value;
					if ((value != null))
					{
						value.FORUM_USERSINROLEs.Add(this);
						this._MEMBER_ID = value.MEMBER_ID;
					}
					else
					{
						this._MEMBER_ID = default(int);
					}
					this.SendPropertyChanged("FORUM_MEMBER");
				}
			}
		}
		
		[Association(Name="FORUM_ROLE_FORUM_USERSINROLE", Storage="_FORUM_ROLE", ThisKey="ROLEID", IsForeignKey=true)]
		public FORUM_ROLE FORUM_ROLE
		{
			get
			{
				return this._FORUM_ROLE.Entity;
			}
			set
			{
				FORUM_ROLE previousValue = this._FORUM_ROLE.Entity;
				if (((previousValue != value) 
							|| (this._FORUM_ROLE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FORUM_ROLE.Entity = null;
						previousValue.FORUM_USERSINROLEs.Remove(this);
					}
					this._FORUM_ROLE.Entity = value;
					if ((value != null))
					{
						value.FORUM_USERSINROLEs.Add(this);
						this._ROLEID = value.RoleID;
					}
					else
					{
						this._ROLEID = default(int);
					}
					this.SendPropertyChanged("FORUM_ROLE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
